version: '3.8'

services:
  # Application service
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://airavate_user:airavate_password@db:5432/airavate_dev?schema=public
      - JWT_SECRET=development-jwt-secret-key
      - JWT_EXPIRES_IN=7d
      - CORS_ORIGIN=http://localhost:3000
      - LOG_LEVEL=debug
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../src:/app/src
      - ../prisma:/app/prisma
    restart: unless-stopped
    networks:
      - airavate-network

  # Database service
  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=airavate_user
      - POSTGRES_PASSWORD=airavate_password
      - POSTGRES_DB=airavate_dev
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U airavate_user -d airavate_dev']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - airavate-network

  # Redis for caching (for future use)
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - airavate-network

  # pgAdmin for database management (development only)
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@airavate.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - airavate-network
    profiles:
      - development

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  airavate-network:
    driver: bridge
